version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - leetgode-network

  leetgode-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - leetgode-network

networks:
  leetgode-network:
    driver: bridge
